# Activation Functions

Activation functions are a crucial component of neural networks. They introduce non-linearity into the network, allowing it to learn complex patterns and make decisions.

## Why Do We Need Activation Functions?

Without activation functions, a neural network would simply be a linear regression model, no matter how many layers it has. The activation function allows the network to approximate any continuous function, making it a universal function approximator.

## Common Activation Functions

### 1. ReLU (Rectified Linear Unit)

The most widely used activation function in modern deep learning.

**Formula:**
$$
f(x) = \max(0, x)
$$

**Characteristics:**
- Outputs 0 for negative inputs
- Outputs the input value for positive inputs
- Computationally efficient
- Helps mitigate the vanishing gradient problem

### 2. Sigmoid

Often used in the output layer for binary classification.

**Formula:**
$$
f(x) = \frac{1}{1 + e^{-x}}
$$

**Characteristics:**
- Outputs values between 0 and 1
- Smooth gradient
- Can suffer from vanishing gradient problem

### 3. Softmax

Used in the output layer for multi-class classification.

**Formula:**
$$
f(x_i) = \frac{e^{x_i}}{\sum_{j} e^{x_j}}
$$

**Characteristics:**
- Outputs a probability distribution
- All outputs sum to 1
- Used for classification problems

## Implementation

Let's implement these activation functions in our neural network code.

In [5]:
# ReLU

inputs = [0, 2, -1, 3.3, -2.7, 1.1, 2.2, -100]

outputs = []

for i in inputs:
    if i > 0:
        outputs.append(i)
    else:
        outputs.append(0)
print(outputs)

[0, 2, 0, 3.3, 0, 1.1, 2.2, 0]


We made up a list of values to start. The ReLU in this code is a loop where we’re checking if the 
current value is greater than 0. If it is, we’re appending it to the output list, and if it’s not, we’re 
appending 0. This can be written more simply, as we just need to take the largest of two values: 0 
or neuron value. For example: 

In [8]:
inputs = [0, 2, -1, 3.3, -2.7, 1.1, 2.2, -100]

outputs = []

for i in inputs:
    outputs.append(max(0, i))

print(outputs)

[0, 2, 0, 3.3, 0, 1.1, 2.2, 0]


**NumPy** contains an equivalent : np.maximum():

In [9]:
import numpy as np

inputs = [0, 2, -1, 3.3, -2.7, 1.1, 2.2, -100]
outputs = np.maximum(0, inputs)

print(outputs)

[0.  2.  0.  3.3 0.  1.1 2.2 0. ]


This method compares each element of the input list (or an array) and returns an object of the same shape filled with new values. We will use it in our new rectified linear activation class:

In [12]:
# ReLU activation:
class Activation_ReLU:

    # forward pass
    def forward(self, inputs):
        # calculate output values from inputs
        self.output = np.maximum(0, inputs)



In [13]:
# Lets apply this to our dense layer !
inputs = [0, 2, -1, 3.3, -2.7, 1.1, 2.2, -100]


class DenseLayer:
    def __init__(self, n_inputs, n_neurons):
        # initialize weights and biases
        self.weights = 0.10 * np.random.rand(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))

    def forward(self, inputs):
        # calculate output values from inputs, weights and biases
        self.output = np.dot(inputs, self.weights) + self.biases

from nnfs.datasets import spiral_data

X,y = spiral_data(samples=100, classes=3)

dense1 = DenseLayer(2,3)

activation1 = Activation_ReLU()
dense1.forward(X)

activation1.forward(dense1.output)

print(activation1.output)

[[0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [6.02744514e-04 2.16341760e-04 3.25197592e-04]
 [1.21324500e-03 4.87031251e-04 7.32514723e-04]
 [1.60602443e-03 1.51544817e-03 2.28572558e-03]
 [1.67589192e-03 0.00000000e+00 0.00000000e+00]
 [1.07413669e-03 2.90954809e-03 4.39438005e-03]
 [3.62528213e-03 2.18129814e-03 3.28612205e-03]
 [3.00151878e-03 4.00099281e-03 6.03830351e-03]
 [4.77298912e-03 3.17084185e-03 4.77834105e-03]
 [7.00169599e-04 4.89267415e-03 7.39283532e-03]
 [0.00000000e+00 4.27151043e-03 6.46025574e-03]
 [7.33549844e-04 5.93255124e-03 8.96443278e-03]
 [8.52828838e-04 6.49251274e-03 9.81041910e-03]
 [0.00000000e+00 5.88016243e-03 8.89139605e-03]
 [6.60011097e-03 7.74528887e-03 1.16868591e-02]
 [0.00000000e+00 6.28863051e-03 9.51158146e-03]
 [6.38543853e-05 8.18892210e-03 1.23767538e-02]
 [0.00000000e+00 5.84398696e-03 8.84531443e-03]
 [0.00000000e+00 7.91486930e-03 1.19692734e-02]
 [3.38334804e-03 1.09146525e-02 1.64866510e-02]
 [0.00000000e+00 7.32463151e-03 1.108382

# The Softmax Activation 

In [ ]:
layer_outputs = [4.8, 1.21, 2.385]

#  e - mathematical constant, we use E here to match a common coding 
# style where constants are uppercased
import math
# e - mathematical constant, we use E here to match a common coding 
# style where constants are uppercased 
E = math.e
# For each value in a vector, calculate the exponential value 

exp_vals = []
for output in layer_outputs:
    exp_vals.append(E ** output)  # ** - power operator in Python
print(exp_vals)

# Now lets normalize values

norm_base = sum(exp_vals)  # We sum all values
norm_vals = []
for value in exp_vals:
    norm_vals.append(value / norm_base)
print(norm_vals)


[121.51041751873483, 3.353484652549023, 10.859062664920513]
[0.8952826639572619, 0.024708306782099374, 0.0800090292606387]


We can perform the same set of operations with the use of NumPy in the following way:

In [18]:
import numpy as np

layer_outputs = [4.8, 1.21, 2.385]

exp_values = np.exp(layer_outputs)
print(exp_values)

norm_values = exp_values / np.sum(exp_values)
print(norm_values)
print(f"Sum of normalized values: {np.sum(norm_values)}")

[121.51041752   3.35348465  10.85906266]
[0.89528266 0.02470831 0.08000903]
Sum of normalized values: 0.9999999999999999


We have some new functions. Specifically, ​np.exp()​ does the ​E​**​output​ part. We should 
also address what ​axis ​and ​keepdims ​mean in the above. Let’s first discuss the ​axis​. Axis is 
easier to show than tell, but, in a 2D array/matrix, axis 0 refers to the rows, and axis 1 refers to 
the columns. Let’s see some examples of how ​axis​ affects the sum using NumPy. First, we 
will just show the default, which is ​None 

In [23]:
import numpy as np

layer_outputs = ([[4.8, 1.21, 2.385],
                  [8.9, -1.81, 0.2],
                  [1.41, 1.051, 0.026]])


print('Sum without axis:', np.sum(layer_outputs))
print('Sum with axis=0:', np.sum(layer_outputs, axis=0))

print("Another way to sum with axis=0:", np.sum(layer_outputs, axis=0, keepdims=True))

Sum without axis: 18.172
Sum with axis=0: [15.11   0.451  2.611]
Another way to sum with axis=0: [[15.11   0.451  2.611]]


This isn’t what we want, though. We want sums of the rows. You can probably guess how to do 
this with NumPy, but we’ll still show the “from scratch” version: 

In [25]:
print("But we want to sum the rows instead, like this w/ raw py:")

for i in layer_outputs:
    print(sum(i))


But we want to sum the rows instead, like this w/ raw py:
8.395
7.29
2.4869999999999997


With the above, we could append these to some list in any way we want. That said, we’re going to 
use NumPy. As you probably guessed, we’re going to sum along axis 1: 

In [ ]:
print('So we can sum axis 1, but note tha current shape:')
print(np.sum(layer_outputs, axis=1))

So we can sum axis 1, but note that curret shape:
[8.395 7.29  2.487]


Now, if we divide the array containing a 
batch of the outputs with this array, NumPy will perform this sample-wise. That means that it’ll 
divide all of the values from each output row by the corresponding row from the sum array.

In [27]:
# Softmax activation:
class Activation_Softmax:
    # forward pass
    def forward(self, inputs):

        # Get unnormalized probabilities
        exp_values = np.exp(inputs - np.max(inputs, axis=1, keepdims=True))

        # Normalize them for each sample
        probabilities = exp_values / np.sum(exp_values, axis=1, keepdims=True)

        self.output = probabilities

# Finally, we also included a subtraction of the largest of the inputs before we did the 
# exponentiation. 

In [28]:
import numpy as np

print(np.exp(1))

2.718281828459045


In [29]:
print(np.exp(10))

22026.465794806718


In [32]:
print(np.exp(100))

2.6881171418161356e+43


In [33]:
print(np.exp(1000))

inf


C:\Users\AGP KOHAT\AppData\Local\Temp\ipykernel_16172\2528843860.py:1: RuntimeWarning: overflow encountered in exp
  print(np.exp(1000))


It doesn’t take a very large number, in this case, a mere ​ 1,000​, to cause an overflow error. We 
know the exponential function tends toward 0 as its input value approaches negative infinity, and 
the output is 1 when the input is 0 (as shown in the chart earlier):

In [34]:
import numpy as np

print(np.exp(-np.inf), np.exp(0))

0.0 1.0


In [35]:
softmax = Activation_Softmax()
softmax.forward([[1,2,3]])
print(softmax.output)

[[0.09003057 0.24472847 0.66524096]]


In [36]:
softmax.forward([[-2,-1,0]])
print(softmax.output)

[[0.09003057 0.24472847 0.66524096]]


This is another useful property of the exponentiated and normalized function. There’s one more 
thing to mention in addition to these calculations. What happens if we divide the layer’s output 
data, ​ [​1​, ​ 2​, ​ 3​]​, for example, by 2? 

In [37]:
softmax.forward([[0.5, 1, 1.5]])
print(softmax.output)

[[0.18632372 0.30719589 0.50648039]]


Now, we can add another dense layer as the output layer, setting it to contain as many inputs as 
the previous layer has outputs and as many outputs as our data includes classes. Then we can 
apply the softmax activation to the output of this new layer: 

In [41]:
# create the dataset
X, y = spiral_data(samples=100, classes=3)

# create the dense layer with 2 input features adn 3 output vals
dense1 = DenseLayer(2,3)

# create ReLU function (to be used with Dense Layer)
activation = Activation_ReLU()


# Create second Dense layer with 3 input features (as we take output 
# of previous layer here) and 3 output values 
dense2 = DenseLayer(3,3)

# Create Softmax activation (to be used with Dense layer):
activation2 = Activation_Softmax()

# make a forward pass of our training data through this layer
dense1.forward(X)


# Make a forward pass through activation function 
# it takes the output of first dense layer here 
activation1.forward(dense1.output)

# Make a forward pass through second Dense layer 
# it takes outputs of activation function of first layer as inputs
dense2.forward(activation1.output)

# Make a forward pass through activation function 
# it takes the output of second dense layer here 
activation2.forward(dense2.output)

print(activation2.output)


[[0.33333333 0.33333333 0.33333333]
 [0.33333297 0.33333067 0.33333636]
 [0.33333118 0.33332681 0.33334201]
 [0.33333546 0.33333456 0.33332998]
 [0.33333049 0.33332034 0.33334916]
 [0.33333459 0.33332763 0.33333778]
 [0.33333522 0.33332764 0.33333714]
 [0.33333887 0.3333385  0.33332263]
 [0.33332635 0.33330617 0.33336748]
 [0.33333382 0.33331809 0.33334809]
 [0.33333494 0.3333193  0.33334577]
 [0.33333297 0.33331223 0.3333548 ]
 [0.33334125 0.33333597 0.33332278]
 [0.33333333 0.33333333 0.33333333]
 [0.33334157 0.3333327  0.33332573]
 [0.33334479 0.33334275 0.33331246]
 [0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33333333]
 [0.33334119 0.33331923 0.33333958]
 [0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33

# Full Code up to this Point 

In [43]:
import numpy as np
import nnfs
from nnfs.datasets import spiral_data

nnfs.init()


# Dense layer
class Layer_Dense:

    # Layer initialization
    def __init__(self, n_inputs, n_neurons):
        # Initialize weights and biases
        self.weights = 0.01 * np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))

    # Forward pass
    def forward(self, inputs):
        # Calculate output values from inputs, weights and biases
        self.output = np.dot(inputs, self.weights) + self.biases


# ReLU activation
class Activation_ReLU:

    # Forward pass
    def forward(self, inputs):
        # Calculate output values from inputs
        self.output = np.maximum(0, inputs)


# Softmax activation
class Activation_Softmax:

    # Forward pass
    def forward(self, inputs):

        # Get unnormalized probabilities
        exp_values = np.exp(inputs - np.max(inputs, axis=1,
                                            keepdims=True))
        # Normalize them for each sample
        probabilities = exp_values / np.sum(exp_values, axis=1,
                                            keepdims=True)

        self.output = probabilities


# Create dataset
X, y = spiral_data(samples=100, classes=3)

# Create Dense layer with 2 input features and 3 output values
dense1 = Layer_Dense(2, 3)

# Create ReLU activation (to be used with Dense layer):
activation1 = Activation_ReLU()

# Create second Dense layer with 3 input features (as we take output
# of previous layer here) and 3 output values (output values)
dense2 = Layer_Dense(3, 3)

# Create Softmax activation (to be used with Dense layer):
activation2 = Activation_Softmax()

# Make a forward pass of our training data through this layer
dense1.forward(X)

# Make a forward pass through activation function
# it takes the output of first dense layer here
activation1.forward(dense1.output)

# Make a forward pass through second Dense layer
# it takes outputs of activation function of first layer as inputs
dense2.forward(activation1.output)

# Make a forward pass through activation function
# it takes the output of second dense layer here
activation2.forward(dense2.output)

# Let's see output of the first few samples:
print(activation2.output[:5])

[[0.33333334 0.33333334 0.33333334]
 [0.3333332  0.3333332  0.33333364]
 [0.3333329  0.33333293 0.3333342 ]
 [0.3333326  0.33333263 0.33333477]
 [0.33333233 0.3333324  0.33333528]]
